import {
  AlertCircle,
  CalendarCheck2,
  CalendarDays,
  ArrowRight,
  ArrowLeft,
  BarChart3,
  Bell,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  CreditCard,
  Download,
  Dumbbell,
  Edit,
  EllipsisVertical,
  ExternalLink,
  FileText,
  Globe,
  Headset,
  Eye,
  Filter,
  FolderOpen,
  GraduationCap,
  LayoutDashboard,
  LifeBuoy,
  LogOut,
  Mail,
  MapPin,
  MoonStar,
  Network,
  Phone,
  Plus,
  Quote,
  RefreshCw,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  SortAsc,
  Sparkles,
  SquareActivity,
  Star,
  Sun,
  TrendingUp,
  Upload,
  UserRound,
  UserCheck,
  Users,
  Wallet,
  XCircle,
  X,
  Diamond,
  BarChart,
  Check,
  Trash2,
  Code,
  Send,
  Car,
  Calendar,
  Video,
  Map,
  Home,
  Menu,
  ChevronUp,
  Clock,
  MessageSquare,
  Building2,
  MapPinned,
  Navigation,
  Route,
  Save,
  History,
  Grid3x3,
  Info,
  Layout,
  DatabaseBackup,
  GitCommit,
  User,
  Zap,
  Lock,
  Terminal,
  Database,
  Cloud,
  RotateCcw,
  Webhook,
  Palette,
  Twitter,
  Linkedin,
  Instagram,
  Youtube,
  FileStack,
  Link2,
  Fingerprint,
  Timer,
  Scale,
  Megaphone,
  Contact,
  Play,
  Copy,
  GitBranch,
  Workflow,
  Gauge,
  TimerOff,
  Split,
  Columns,
  Share2,
  BookOpen,
  PlayCircle,
  Folder,
  Award,
  Inbox,
  Paperclip,
  Trophy,
  Tag,
  Briefcase,
  Archive,
  DoorOpen,
  Shield,
  Volume2,
  VolumeX,
  Scroll,
  LogIn,
  Key,
  EyeOff,
  UserPlus,
  Building,
  Badge,
  Handshake,
  Camera,
  ToggleRight,
  Unlock,
} from 'lucide-react';

const iconMap = {
  add: Plus,
  activity: SquareActivity,
  sensors: SquareActivity,
  upload_file: Upload,
  done_all: CheckCircle2,
  analytics: BarChart3,
  calendar_today: CalendarDays,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  date_range: CalendarDays,
  download: Download,
  auto_awesome: Sparkles,
  event_available: CalendarCheck2,
  call: Phone,
  cancel: XCircle,
  check_circle: CheckCircle2,
  contrast: MoonStar,
  dashboard: LayoutDashboard,
  dashboard_customize: LayoutDashboard,
  description: FileText,
  edit: Edit,
  filter_list: Filter,
  folder_open: FolderOpen,
  assignment: FolderOpen,
  format_quote: Quote,
  group: Users,
  groups: Users,
  help: CircleHelp,
  help_center: LifeBuoy,
  how_to_reg: UserCheck,
  hub: Network,
  light_mode: Sun,
  language: Globe,
  location_on: MapPin,
  logout: LogOut,
  mail: Mail,
  email: Mail,
  more_vert: EllipsisVertical,
  monitoring: BarChart3,
  notifications: Bell,
  open_in_new: ExternalLink,
  person_pin: UserRound,
  payments: CreditCard,
  refresh: RefreshCw,
  rocket_launch: Rocket,
  school: GraduationCap,
  search: Search,
  security: ShieldCheck,
  settings: Settings,
  sort: SortAsc,
  sports_kabaddi: Dumbbell,
  star: Star,
  support: Headset,
  support_agent: Headset,
  task_alt: CheckCircle2,
  today: CalendarDays,
  trending_up: TrendingUp,
  upload: Upload,
  verified_user: UserCheck,
  visibility: Eye,
  warning: AlertCircle,
  account_balance_wallet: Wallet,
  bar_chart_3: BarChart3,
  bar_chart: BarChart,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  check: Check,
  delete: Trash2,
  diamond: Diamond,
  code: Code,
  send: Send,
  directions_car: Car,
  schedule: Calendar,
  video_call: Video,
  video: Video,
  map: Map,
  home: Home,
  menu: Menu,
  photo_camera: Camera,
  close: X,
  clock: Clock,
  message: MessageSquare,
  building: Building2,
  map_pinned: MapPinned,
  navigation: Navigation,
  route: Route,
  save: Save,
  history: History,
  category: Grid3x3,
  info: Info,
  contact_mail: Mail,
  layout: Layout,
  backup: DatabaseBackup,
  commit: GitCommit,
  remove_circle: XCircle,
  person: User,
  chat: MessageSquare,
  speed: Zap,
  lock: Lock,
  web: Globe,
  terminal: Terminal,
  storage: Database,
  cloud: Cloud,
  autorenew: RotateCcw,
  webhook: Webhook,
  palette: Palette,
  ads_click: Megaphone,
  grid_view: Grid3x3,
  compare: Split,
  timeline: Clock,
  twitter: Twitter,
  linkedin: Linkedin,
  instagram: Instagram,
  youtube: Youtube,
  extension: Workflow,
  gavel: Scale,
  campaign: Megaphone,
  contact_phone: Phone,
  timer: Timer,
  fingerprint: Fingerprint,
  link2: Link2,
  play: Play,
  copy: Copy,
  split: Split,
  columns: Columns,
  share: Share2,
  menu_book: BookOpen,
  card_membership: Award,
  play_circle: PlayCircle,
  picture_as_pdf: FileText,
  payment_gateways: CreditCard,
  folder: Folder,
  image: FileText,
  inbox: Inbox,
  attach_file: Paperclip,
  emoji_events: Trophy,
  grade: Scroll,
  results: Scroll,
  event: CalendarDays,
  headset: Headset,
  offer: Tag,
  publish: Upload,
  receipt: FileText,
  room: DoorOpen,
  shield_check: Shield,
  verified: ShieldCheck,
  work: Briefcase,
  sync: RefreshCw,
  login: LogIn,
  visibility_off: EyeOff,
  person_add: UserPlus,
  public: Globe,
  key: Key,
  phone: Phone,
  business: Building,
  badge: Badge,
  partner: Handshake,
  partners: Handshake,
  pending: Clock,
  // TempUrls Icons
  admin_panel_settings: ShieldCheck,
  handshake: Handshake,
  auto_stories: BookOpen,
  expand_more: ChevronDown,
  open_in_new_tab: ExternalLink,
  lock_reset: Unlock,
  toggle_on: ToggleRight,
};

export default function AppIcon({ name, className, strokeWidth = 2, ...props }) {
  const Icon = iconMap[name] ?? CircleHelp;
  if (Icon === CircleHelp) {
    console.warn(`Icon not found fix it: ${name}`);
  }

  return <Icon aria-hidden="true" className={className} strokeWidth={strokeWidth} {...props} />;
}