# Generated by Django 6.0.6 on 2026-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('ACCOUNTANT', 'Accountant'), ('HOD', 'Head Of Department'), ('RECEPTIONIST', 'Receptionist')], default='STUDENT', max_length=30),
        ),
    ]
